---
- name: Gather basic information about localhost
  hosts: localhost
  gather_facts: false
  vars:
  tasks:
  - name: gather uptime
    ansible.builtin.shell: "awk -F: '{ print $1}' /etc/passwd"
    register: my_user
      
  - name: show my gathered uptime
    ansible.builtin.debug:
#      var: ansible_facts
      var: my_users
