---
- name: Gather facts from our router and perform some conditional tests
  hosts: rtr1
  gather_facts: false
  vars:
    required_version: 16.06.01
  tasks:
    - name: Gather facts from the router
      cisco.ios.ios_facts:
        gather_subset: min
        gather_network_resources: snmp_server
      register: facts

    - name: Display facts
      ansible.builtin.debug:
        var: facts

    - name: "Display message when OS version is {{ required_version }}"
      when: facts.ansible_facts.ansible_net_version == required_version
      ansible.builtin.debug:
        msg: "The OS version is secure"

    - name: "Display message when OS version is not {{ required_version }}"
      when: facts.ansible_facts.ansible_net_version != required_version
      ansible.builtin.debug:
        msg: "The OS version is {{ facts.ansible_facts.ansible_net_version }}"

    - name: "Display message when OS version is not {{ required_version }} and public community is ro"
      when: facts.ansible_facts.ansible_net_version != required_version and facts.ansible_facts.ansible_network_resources.snmp_server.communities[1].ro == "true"
      ansible.builtin.debug:
        msg: "FAILURE-The OS version is {{ facts.ansible_facts.ansible_net_version }} and public community is RO"