---
- name: Gather facts from our switch and perform some conditional tests
  hosts: sw1
  gather_facts: false
  vars:
    required_version: 9.3(3)
  tasks:
    - name: Gather facts from the switch
      cisco.nxos.nxos_facts:
        gather_subset: min
        gather_network_resources: snmp_server
      register: facts

    - name: Display facts
      ansible.builtin.debug:
        var: facts

    - name: "Display message when OS version is not {{ required_version }}"
      when: facts.ansible_facts.ansible_net_version != required_version
      ansible.builtin.debug:
        msg: "FAILURE-The OS version is {{ facts.ansible_facts.ansible_net_version }}"