---
- name: Gather facts from our switch and perform some conditional tests
  hosts: sw1
  gather_facts: false
  tasks:
    - name: Gather facts from the switch
      cisco.nxos.nxos_facts:
        gather_subset: min
        gather_network_resources: snmp_server
      register: facts

    - name: Display facts
      ansible.builtin.debug:
        var: facts