---
- name: Make an ansible shell command idempotent...if possible
  hosts: Greg-rocky9
  gather_facts: false
  vars:
  tasks:
#  echo "i'm always hungry" > test1.txt
    - name: create test file
      ansible.builtin.copy:
        content: I'm always hungry"
        dest: /tmp/test1.txt

# [root@Greg-rocky9 ~]# rm test1.txt -fv
# removed 'test1.txt'
    - name: delete a test file using shell, but make it idempotent
      ansible.builtin.shell: rm /tmp/test1.txt -fv
      register: remove_check
      changed_when: "'removed' in remove_check.stdout"

    - name: delete a second test file using shell, but make it idempotent
      ansible.builtin.shell: rm /tmp/test2.txt -fv
      register: remove_check2
      changed_when: "'removed' in remove_check2.stdout"