---
- name: Idempotent shell scripts
  hosts: Greg-rocky9
  gather_facts: false
  vars:
  tasks:
    - name: Create a dummy file
      ansible.builtin.copy:
        content: I'm always hungry
        dest: /tmp/test1.txt

    - name: Delete the dummy file
      ansible.builtin.shell: rm /tmp/test1.txt -fv
      register: remove_check
      changed_when: "'removed' in remove_check.stdout"
      
      
    - name: Delete a second dummy file
      ansible.builtin.shell: rm /tmp/test2.txt -fv
      