# playbook.yml
---
- name: A demo on using include vs import in Ansible with incorrect info
  hosts: localhost
  gather_facts: false
  vars:
    testvar: "Initial Value"  # Initial value for the variable
  tasks:
    - name: Display initial testvar value
      ansible.builtin.debug:
        msg: "Before import_tasks and include_tasks: testvar is {{ testvar }}"

    - name: Use import_tasks (static)
      import_tasks: tasks/import-tasks.yml

    - name: Update testvar to "Updated Value"
      set_fact:
        testvar: "Updated Value"

    - name: Use include_tasks (dynamic)
      include_tasks: tasks/include-tasks.yml

    - name: Re-run import_tasks after update
      import_tasks: tasks/import-tasks.yml
