# playbook.yml
---
- name: Demo showing import_tasks vs include_tasks with loop
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Set list of items
      set_fact:
        item_list:
          - one
          - two
          - three

    - name: Use import_tasks with a loop (static)
      import_tasks: tasks/loop-tasks.yml
      loop: "{{ item_list }}"
      when: "'three' not in item_list"

    - name: Modify item_list to remove 'three'
      set_fact:
        item_list: "{{ item_list | difference(['three']) }}"

    - name: Use include_tasks with a loop (dynamic)
      include_tasks: tasks/loop-tasks.yml
      loop: "{{ item_list }}"
      when: "'three' not in item_list"
