---
- name: install apache on rocky 9
  hosts: Greg-rocky9
  become: yes
  tasks:
    - name: install apache
      package:
        name: httpd
        state: present
    - name: start apache
      service:
        name: httpd
        state: started
        enabled: yes