---
- name: Install Apache
  hosts: Greg-rocky9
  gather_facts: false
  become: true
  tasks:
    - name: Install Apache
      ansible.builtin.dnf:
        name: httpd
        state: present
    - name: Start Apache
      ansible.builtin.service:
        name: httpd
        state: started
    - name: Enable Apache
      ansible.builtin.service:
        name: httpd
        enabled: yes