---
- name: A demo showing how nested loops work in Ansible
  hosts: localhost
  gather_facts: false
  vars:
    match_user:
      - root
      - tss
  tasks:
    - name: Gather list of users from the linux server using the shell module
      ansible.builtin.shell: 'cat /etc/passwd | cut -d: -f1'
      register: users
      changed_when: false
        
    # - name: Debug users variable
    #   ansible.builtin.debug:
    #     var: users.stdout_lines

    # - name: Block for just getting counts of files owned by users
    #   when: 'current_user in match_user'
    #   block:
    #     - name: Count of files owned by this user
    #       ansible.builtin.shell: "find / -user {{ current_user }} | wc -l"
    #       register: files_count
    #       changed_when: false

    #     - name: "Add additional items to the total_files list for {{ current_user }}"
    #       set_fact:
    #         total_files: "{{ total_files | default([]) + [current_user ~ ' - ' ~ files_count.stdout] }}"
    #       when: files_count.stdout != "0"

    - name: Outer loop - we go over our main loop and call a task file
      when: 'current_user in match_user'
      include_tasks: tasks/inner-loop.yml
      loop: "{{ users.stdout_lines }}"
      loop_control:
        loop_var: current_user

    - name: Debug total_files variable
      ansible.builtin.debug:
        var: total_files