---
- name: Configure a Cisco Nexus switch to utilize ssh public keys
  hosts: nexus9k1
  gather_facts: false
  vars:
    automation_username: "automation"
    # This data should really be supplied via a vault or stored as a file and using the file lookup plugin
    key_content: "ssh-rsa 111222333444555666aaabbbb"
    
  tasks:
    # - name: Create the public key file for use with the nxos_user module
    #   ansible.builtin.copy:
    #     content: "{{ key_content }}"
    #     dest: /tmp/id_rsa.pub
    #     mode: 0600
    #   delegate_to: localhost
    #   run_once: true

    - name: Add the public key to the Nexus switch
      cisco.nxos.nxos_user:
        name: "{{ automation_username }}"
        # sshkey: "{{ lookup('file', '/tmp/id_rsa.pub') }}"
        sshkey: "{{ key_content }}"
        state: present