---
- name: Various test of the set_stats module
  hosts: all
  # gather_facts: false
  vars:
  tasks:
#  - name: spit out gathered facts
#    ansible.builtin.debug:
#      var: ansible_facts
# distribution_version
  - name: per_host false and aggregate true- default behavior
    ansible.bultin.set_stats:
      data:
        dist_ver_per_host_false_agg_true: "{{ ansible_facts.distribution_version }}"
    per_host: false

  - name: per_host true and aggregate true
    ansible.bultin.set_stats:
      data:
        dist_ver_per_host_true_agg_true: "{{ ansible_facts.distribution_version }}"
    per_host: true

  - name: per_host false and aggregate false
    ansible.bultin.set_stats:
      data:
        dist_ver_per_host_false_agg_true: "{{ ansible_facts.distribution_version }}"
    per_host: false
    aggregate: false

  - name: per_host true and aggregate false
    ansible.bultin.set_stats:
      data:
        dist_ver_per_host_true_agg_true: "{{ ansible_facts.distribution_version }}"
    per_host: true
    aggregate: false

    - name: show info
      ansible.builtin.debug:
        msg: |
          "dist_ver_per_host_false_agg_true = {{ dist_ver_per_host_false_agg_true }}
          dist_ver_per_host_true_agg_true = {{ dist_ver_per_host_true_agg_true }}
          dist_ver_per_host_false_agg_true = {{ dist_ver_per_host_false_agg_true }}
          dist_ver_per_host_true_agg_true = {{ dist_ver_per_host_true_agg_true }}"
