---
- name: Various test of the set_stats module
  hosts: all
  # gather_facts: false
  vars:
    show_custom_stats: true
  tasks:
#  - name: spit out gathered facts
#    ansible.builtin.debug:
#      var: ansible_facts
# distribution_version
  - name: per_host false and aggregate true- default behavior
    ansible.builtin.set_stats:
      data:
        dist_ver_per_host_false_agg_true: "{{ ansible_facts.distribution_version }}"
      per_host: false

  - name: per_host true and aggregate true
    ansible.builtin.set_stats:
      data:
        dist_ver_per_host_true_agg_true: "{{ ansible_facts.distribution_version }}"
      per_host: true

  - name: per_host false and aggregate false
    ansible.builtin.set_stats:
      data:
        dist_ver_per_host_false_agg_false: "{{ ansible_facts.distribution_version }}"
      per_host: false
      aggregate: false

  - name: per_host true and aggregate false
    ansible.builtin.set_stats:
      data:
        dist_ver_per_host_true_agg_false: "{{ ansible_facts.distribution_version }}"
      per_host: true
      aggregate: false

  - name: set fact
    ansible.builtin.set_fact:
      per_host_fact: "{{ per_host_fact | default({}) | combine({ item : { 'ver' : lookup('vars', item + '.ansible_facts.distribution_version')}})}}"
    loop: "{{ play_hosts }}"
    run_once: true
      
  - name: per host collection and aggregate false via a workaround
    ansible.builtin.set_stats:
      data:
        # dist_ver_per_host_agg_false: "{{ dist_ver_per_host_agg_false | default ({}) | combine({ 'key': inventory_hostname : 'value': ansible_facts.distribution_version)}}"
        # dist_ver_per_host_agg_false: "{{ dist_ver_per_host_agg_false | default ({}) | combine({ inventory_hostname : { 'ver' : ansible_facts.distribution_version}})}}"
        # dist_ver_per_host_agg_false: "{{ dist_ver_per_host_agg_false | default ({}) | combine({ inventory_hostname : { 'ver' : ansible_facts.distribution_version}}, list_merge='append_rp')}}"
        # dist_ver_per_host_agg_false: "{{ dist_ver_per_host_agg_false | default ({}) | combine({ inventory_hostname : { 'ver' : ansible_facts.distribution_version}})}}"
        dist_ver_per_host_agg_false: "{{ per_host_fact }}"
      aggregate: false
    run_once: true

#  - name: show info
#    ansible.builtin.debug:
#      msg:
#        - "dist_ver_per_host_false_agg_true = {{ dist_ver_per_host_false_agg_true }}"
#        - "dist_ver_per_host_true_agg_true = {{ dist_ver_per_host_true_agg_true }}"
#        - "dist_ver_per_host_false_agg_false = {{ dist_ver_per_host_false_agg_false }}"
#        - "dist_ver_per_host_true_agg_false = {{ dist_ver_per_host_true_agg_false }}"
