---
- name: SNMP updates
  hosts: sw1
  gather_facts: false
  tasks:
    - name: Replace existing SNMP configuration with the nxos_snmp_server module
      cisco.nxos.nxos_snmp_server:
        config:
          communities:
            - community: public
              group: network-operator
            # - community: private
            #   group: network-admin
        state: replaced

    - name: Find current SNMP configuration
      cisco.nxos.nxos_command:
        commands: show run | inc community
      register: snmp_output

    - name: Display current SNMP configuration
      ansible.builtin.debug:
        var: snmp_output.stdout_lines