---
- name: SNMP updates
  hosts: rtr1
  gather_facts: false

  tasks:
    - name: Parse config
      cisco.ios.ios_snmp_server:
        running_config: "{{ lookup('file', 'files/snmp.txt') }}"
        state: parsed
      register: parsed

    - name: Display parsed SNMP configuration
      ansible.builtin.debug:
        var: parsed

    - name: Replace existing SNMP configuration with the ios_snmp_server module
      cisco.ios.ios_snmp_server:
        config: "{{ parsed.parsed }}"
        state: replaced 

    - name: Find current SNMP configuration
      cisco.ios.ios_command:
        commands: show run | inc community
      register: snmp_output

    - name: Display current SNMP configuration
      ansible.builtin.debug:
        var: snmp_output.stdout_lines
