---
- name: SNMP updates
  hosts: sw1
  gather_facts: false
  tasks:
    - name: Parse config
      cisco.nxos.nxos_snmp_server:
        running_config: "{{ lookup('file', 'files/snmp.txt') }}"
        state: parsed
      register: parsed

    - name: Display parsed SNMP configuration
      ansible.builtin.debug:
        var: parsed

    - name: Replace existing SNMP configuration with the nxos_snmp_server module
      cisco.nxos.nxos_snmp_server:
        config: "{{ parsed.parsed }}"
          # communities:
            # - name: public
            #   group: network-operator
            # - name: private
            #   group: network-admin
        state: replaced 

    - name: Find current SNMP configuration
      cisco.nxos.nxos_command:
        commands: show run | inc community
      register: snmp_output

    - name: Display current SNMP configuration
      ansible.builtin.debug:
        var: snmp_output.stdout_lines