---
- name: SNMP updates
  hosts: rtr1
  gather_facts: false
  tasks:
    - name: Configure SNMP with the config module
      cisco.ios.ios_config:
        lines:
          - snmp-server community public group network-operator
          - snmp-server community private group network-admin

    - name: Find current SNMP configuration
      cisco.ios.ios_command:
        commands: show run | inc community
      register: snmp_output

    - name: Display current SNMP configuration
      ansible.builtin.debug:
        var: snmp_output.stdout_lines
