---
- name: Create VLANs on DC switches that are passed as extra vars
  hosts: sw1
  gather_facts: false
  vars:
    vlans:
      - vlan_id: 10
        name: web
      - vlan_id: 20
        name: app

  tasks:
    - name: Create VLANs
      cisco.nxos.nxos_vlans:
        config: "{{ vlans }}"

    - name: some filter testing
      ansible.builtin.debug:
        var: vlans | map(attribute='vlan_id') | flatten #| list 

    # Ethernet1/10
    - name: Assign vlans to the vlan allow list on the trunk port
      cisco.nxos.nxos_l2_interfaces:
        config:
          - name: Ethernet1/10
            trunk:
              allowed_vlans: "{{ vlans | map(attribute='vlan_id') | list }}"
#      loop: "{{ vlans }}" 