---
- name: Quick test of Github webook variables sent
  hosts: localhost
  gather_facts: false
  vars:
    test: 12345
  tasks:
    - name: Print out the full awx_webhook_payload
      ansible.builtin.debug:
        var: awx_webhook_payload

    - name: Print out the name of all files modified
      ansible.builtin.debug:
        #var: item.modified
        msg: "{{ item }}"
      loop: "{{ awx_webhook_payload.commits[0].modified }}"