---
- name: Quick webserver install and configure
  hosts: LL-rocky9-01
  gather_facts: false
  become: true
  tasks:
    - name: Install apache webserver
      ansible.builtin.package:
        name: httpd
        state: present
    
    - name: Start and enable apache
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Write a simple index.html file
      ansible.builtin.lineinfile:
        # path: /usr/share/nginx/html/index.html
        path: /var/www/html/index.html
        # line: "<html><body><h1>Hello World!</h1></body></html>"
        line: "<h1>Hello World!</h1>"
        create: true