---
- name: Block for tss found files
  when: current_user == "tss"
  ignore_errors: true
  block:
    - name: Files owned by tss user
      ansible.builtin.shell: "find / -user {{ current_user }}"
      register: found_files
      changed_when: false
      failed_when: false

    - name: "Debug found_files variable for {{ current_user }}"
      when: found_files.stdout != ""
      ansible.builtin.debug:
        var: found_files.stdout_lines

    - name: Examine file permissions for found_files.stdout_lines
      ansible.builtin.shell: "ls -la {{ item }}"
      loop: "{{ found_files.stdout_lines }}"
      register: file_permissions_check

    - name: debug file_permissions_check variable
      when: file_permissions_check.stdout | default("") != ""
      ansible.builtin.debug:
        var: file_permissions_check.stdout_lines

- name: Count of files owned by this user
  ansible.builtin.shell: "find / -user {{ current_user }} | wc -l"
  register: files_count
  changed_when: false

# - name: Debug files_count variable
#   when: files_count.stdout != "0"
#   ansible.builtin.debug:
#     msg: "{{ current_user }} - {{ files_count.stdout }}"

- name: "Add additional items to the total_files list for {{ current_user }}"
  set_fact:
    total_files: "{{ total_files | default([]) + [current_user ~ ' - ' ~ files_count.stdout] }}"
  when: files_count.stdout != "0"