---
- name: Count of files owned by this user
  ansible.builtin.shell: "find / -user {{ current_user }} | wc -l"
  register: files_count

- name: Debug files_count variable
  ansible.builtin.debug:
    msg: "{{ current_user }} - {{ files_count.stdout }}"